TalkingWebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from . import views
from django.contrib import admin
# from django.urls import path
from django.views.generic import RedirectView


urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^talkingtree/',  include('talkingtree.urls')),
]

urlpatterns += [
    url('', RedirectView.as_view(url='/talkingtree/')),
]

talkingtree/urls.py
from django.conf.urls import url
# from django.contrib import admin
# from django.conf import settings
# from django.conf.urls.static import static
# from talkingtree.views import views
# from . import views

from talkingtree.views import user, question, answer, voteanswer, comment, votecomment

# from django.contrib import admin
# from django.urls import path
# from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

app_name ='talkingtree'
urlpatterns = [

    url(r'^register/$', user.UserFormView.as_view(), name='register'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),

    url(r'^$', question.QuestionView.as_view(), name='question'),
    url(r'^myquestions/$', question.myquestions, name='myquestions'),
    url(r'^searchquestions/$', question.searchquestions, name='searchquestions'),
    url(r'^question/add/$', question.QuestionCreate.as_view(), name='add-question'),
    url(r'^questions/(?P<pk>[0-9]+)/update$', question.QuestionUpdate.as_view(), name='update-question'),
    url(r'^questions/(?P<pk>[0-9]+)/delete/$', question.QuestionDelete.as_view(), name='delete-question'),

    url(r'^questions/(?P<question_id>[0-9]+)/answers/$', answer.answer, name='answer'),
    url(r'^questions/(?P<question_id>[0-9]+)/answers/add/$', answer.AnswerCreate.as_view(), name='add-answer'),
    url(r'^questions/(?P<question_id>[0-9]+)/answers/(?P<pk>[0-9]+)/update$', answer.AnswerUpdate.as_view(), name='update-answer'),
    url(r'^questions/(?P<question_id>[0-9]+)/answers/(?P<pk>[0-9]+)/delete/$', answer.AnswerDelete.as_view(), name='delete-answer'),
    url(r'^myanswers/$', answer.myanswers, name='myanswers'),

    url(r'^questions/(?P<question_id>[0-9]+)/answers/(?P<answer_id>[0-9]+)/comments/$', comment.comment, name='comment'),
    url(r'^questions/(?P<question_id>[0-9]+)/answers/(?P<answer_id>[0-9]+)/comments/(?P<pk>[0-9]+)/update$', comment.CommentUpdate.as_view(), name='update-comment'),
    url(r'^questions/(?P<question_id>[0-9]+)/answers/(?P<answer_id>[0-9]+)/comments/(?P<pk>[0-9]+)/delete/$', comment.CommentDelete.as_view(), name='delete-comment'),
    url(r'^questions/(?P<question_id>[0-9]+)/answers/(?P<answer_id>[0-9]+)/comments/add/$', comment.CommentCreate.as_view(), name='add-comment'),

    url(r'^answer/(?P<answer_id>[0-9]+)/upvotes_answer/$', voteanswer.create_voteanswer, name='upvotes_answer'),
    url(r'^answer/(?P<answer_id>[0-9]+)/downvotes_answer/$', voteanswer.create_downvoteanswer, name='downvotes_answer'),

    url(r'^answer/(?P<comment_id>[0-9]+)/upvotes_comment/$', votecomment.create_votecomment, name='upvotes_comment'),
    url(r'^answer/(?P<comment_id>[0-9]+)/downvotes_comment/$', votecomment.create_downvotecomment, name='downvotes_comment'),

    url(r'^account/profile/$', user.profile_view, name='profile'),
    url(r'^account/profile/(?P<pk>[0-9]+)/update$', user.UserUpdate.as_view(), name='update_user'),
]

talkingtree/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Question, Answer, Comment


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']


class NewQuestionForm(forms.Form):
    question = forms.CharField(widget=forms.Textarea)
    question.widget.attrs.update({'class': 'special'})

    class Meta:
        model = Question
        fields = ['user', 'question_text']


class NewAnswerForm(forms.Form):
    answer = forms.CharField(widget=forms.Textarea)
    answer.widget.attrs.update({'class': 'special'})

    class Meta:
        model = Answer
        fields = ['user', 'question', 'answer_text']


class NewCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)
    comment.widget.attrs.update({'class': 'special'})

    class Meta:
        model = Comment
        fields = ['user', 'answer', 'comment_text']

talkingtree/views/answer.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import Http404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth import login, authenticate
from django.views.generic import View
from talkingtree.models import Question, Answer, Voteanswer
from talkingtree.forms import NewAnswerForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView


# class AnswerView(generic.ListView):
#     template_name = 'talkingtree/index.html'
#     context_object_name = 'all_answer'
#     paginate_by = 5
#
#     def get_queryset(self):
#         return Answer.objects.all()
#

class AnswerCreate(View):
    template_name = 'talkingtree/question_form.html'
    form_class = NewAnswerForm

    def get(self, request, question_id):
        if request.user.is_authenticated:
            form = self.form_class(None)
            q = Question.objects.get(pk=question_id)
            return render(request, self.template_name, {'form': form, 'question':q})
        else:
            return redirect('talkingtree:login')

    def post(self, request, question_id):
        form = self.form_class(request.POST)
        if form.is_valid():
            que = Question.objects.get(pk=question_id)
            answer = Answer(user=request.user, question=que, answer_text=form.cleaned_data['answer'])
            answer.save()
        return redirect('talkingtree:answer', question_id)


class AnswerDelete(DeleteView):
    model = Answer
    fields = ['question', 'user', 'answer_text', 'created_date',]
    success_url = reverse_lazy('talkingtree:question')

class AnswerUpdate(FormView):
    template_name = 'talkingtree/question_form.html'
    form_class = NewAnswerForm

    def get(self, request, question_id, pk):
        if request.user.is_authenticated:
            answer = Answer.objects.get(pk=pk)
            question = Question.objects.get(pk=question_id)
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form, 'question': question, 'answer':answer})
        else:
            return redirect('talkingtree:login')

    def post(self, request, question_id, pk):
        form_class = NewAnswerForm
        form = self.form_class(request.POST)
        if form.is_valid():
            answer = Answer.objects.get(pk=pk)
            answer.answer_text = form.cleaned_data['answer']
            answer.save()
        return redirect('talkingtree:answer', question_id)


def answer(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        answers = Answer.objects.filter(question_id=question_id)
        count_answer = answers.count();
        answers_list = []
        for answer in answers:
            count_upvote = Voteanswer.objects.filter(vote=True, answer=answer).count()
            count_downvote = Voteanswer.objects.filter(vote=False, answer=answer).count()
            count_uservote = None
            if request.user.is_authenticated:
                count_uservote = Voteanswer.objects.filter(user=request.user, answer=answer).count()
            if count_uservote > 0:
                uservote = Voteanswer.objects.filter(user=request.user, answer=answer).first()
                answers_list.append({
                    'answer': answer,
                    'vote': uservote.vote,
                    'count_upvoteanswer': count_upvote,
                    'count_downvoteanswer': count_downvote
                })
            else:
                answers_list.append({
                    'answer':answer,
                    'vote': None,
                    'count_upvoteanswer':count_upvote,
                    'count_downvoteanswer':count_downvote
                })
    except Question.DoesNotExist:
        raise Http404('Answer Does not Exist.')
    return render(request, 'talkingtree/answer.html', {
        'question' : question, 'all_answer': answers_list, 'count_answer': count_answer,})


@login_required
def myanswers(request):
    try:
        answers = Answer.objects.filter(user=request.user)
        count_answer = answers.count()
        answers_list = []
        for answer in answers:
            count_upvote = Voteanswer.objects.filter(vote=True, answer=answer).count()
            count_downvote = Voteanswer.objects.filter(vote=False, answer=answer).count()
            answers_list.append({
                'answer':answer,
                'count_upvoteanswer':count_upvote,
                'count_downvoteanswer':count_downvote
            })

    except Question.DoesNotExist:
        raise Http404('Answer Does not Exist.')
    return render(request, 'talkingtree/myanswers.html', {
       'all_answer': answers_list, 'count_answer': count_answer,})

talkingtree/views/comment.py
from talkingtree.models import Comment, Votecomment
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import Http404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import View
from talkingtree.models import Question, Answer
from talkingtree.forms import NewCommentForm
from django.views.generic.edit import FormView

# class CommentCreate(CreateView):
#     model = Comment
#     fields = ['answer', 'user', 'comment_text',]
#     success_url = reverse_lazy('talkingtree:question')


class CommentCreate(View):
    template_name = 'talkingtree/question_form.html'
    form_class = NewCommentForm

    def get(self, request, question_id, answer_id):
        if request.user.is_authenticated:
            form = self.form_class(None)
            q = Question.objects.get(pk=question_id)
            a = Answer.objects.get(pk=answer_id)
            return render(request, self.template_name, {'form': form, 'question': q, 'answer': a})
        else:
            return redirect('talkingtree:login')

    def post(self, request, question_id, answer_id):
        form = self.form_class(request.POST)
        if form.is_valid():
            # que = Question.objects.get(pk=question_id)
            ans = Answer.objects.get(pk=answer_id)
            comment = Comment.objects.create(user=request.user, answer=ans, comment_text=form.cleaned_data['comment'])
            comment.save()
        return redirect('talkingtree:comment', question_id, answer_id)



class CommentDelete(DeleteView):
    model = Comment
    fields = ['answer', 'user', 'comment_text','created_date',]
    success_url = reverse_lazy('talkingtree:question')


class CommentUpdate(FormView):
    template_name = 'talkingtree/question_form.html'
    form_class = NewCommentForm

    def get(self, request, question_id, answer_id, pk):
        if request.user.is_authenticated:
            comment = Comment.objects.get(pk=pk)
            answer = Answer.objects.get(pk=answer_id)
            question = Question.objects.get(pk=question_id)
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form,'question': question, 'answer':answer, 'comment':comment})
        else:
            return redirect('talkingtree:login')

    def post(self, request, question_id, answer_id, pk):
        form_class = NewCommentForm
        form = self.form_class(request.POST)
        if form.is_valid():
            comment = Comment.objects.get(pk=pk)
            answer = Answer.objects.get(pk=answer_id)
            question = Question.objects.get(pk=question_id)
            comment.comment_text = form.cleaned_data['comment']
            comment.save()
        return redirect('talkingtree:comment', question_id, answer_id, )

# class CommentUpdate(UpdateView):
#     model = Comment
#     fields = ['answer', 'user', 'comment_text',]
#     success_url = reverse_lazy('talkingtree:question')
#


# @login_required

def comment(request, question_id, answer_id):
    try:
        answer = Answer.objects.get(pk=answer_id)
        # question = Question.objects.filter(pk = question_id)
        question = Question.objects.filter(answer__id=answer_id).first()
        comments = Comment.objects.filter(answer = answer)
        count_comment = answer.comment_set.count();
        comments_list = []

        for comment in comments:
            count_votecomment = Votecomment.objects.filter(vote=True, comment=comment).count()
            count_downvotecomment = Votecomment.objects.filter(vote=False, comment=comment).count()
            count_uservotecomment = None
            if request.user.is_authenticated:
                count_uservotecomment = Votecomment.objects.filter(user=request.user, comment=comment).count()
            if count_uservotecomment > 0:
                votecomment = Votecomment.objects.filter(user=request.user, comment=comment).first()
                comments_list.append(
                    {
                        'comment': comment,
                        'vote': votecomment.vote,
                        'count_upvotecomment': count_votecomment,
                        'count_downvotecomment': count_downvotecomment
                    }
                )
            else:
                comments_list.append(
                    {
                        'comment': comment,
                        'vote': None,
                        'count_upvotecomment': count_votecomment,
                        'count_downvotecomment': count_downvotecomment
                    }
                )
    except Question.DoesNotExist:
        raise Http404('comment Does not Exist.')
    return render(request, 'talkingtree/comment.html', {'question':question, 'answer' : answer,
                                                         'all_comment': comments_list, 'count_comment':count_comment,
                                                        })

talkingtree/views/question.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import Http404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import View
from talkingtree.models import Question
from talkingtree.forms import UserForm, NewQuestionForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView


class QuestionView(generic.ListView):
    template_name = 'talkingtree/index.html'
    context_object_name = 'questions'
    paginate_by = 5

    def get_queryset(self):
        return Question.objects.all()


class QuestionCreate(View):
    template_name = 'talkingtree/question_form.html'
    form_class = NewQuestionForm

    def get(self, request):
        if request.user.is_authenticated:
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('talkingtree:login')

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            question = Question.objects.create(user=request.user, question_text=form.cleaned_data['question'])
            question.save()
        return redirect('talkingtree:question')


class QuestionUpdate(FormView):
    template_name = 'talkingtree/question_form.html'
    form_class = NewQuestionForm

    def get(self, request, pk):
        if request.user.is_authenticated:
            question = Question.objects.get(pk=pk)
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form, 'question':question})
        else:
            return redirect('talkingtree:login')

    def post(self, request, pk):
        form_class = NewQuestionForm
        form = self.form_class(request.POST)
        if form.is_valid():
            question = Question.objects.get(pk=pk)
            question.question_text = form.cleaned_data['question']
            question.save()
        return redirect('talkingtree:question')


class QuestionDelete(DeleteView):
    model = Question
    fields = ['user', 'question_text']
    success_url = reverse_lazy('talkingtree:question')


@login_required
def myquestions(request):
    try:
        questions = Question.objects.filter(user=request.user)
        count_question= questions.count()
    except Question.DoesNotExist:
        raise Http404('Answer Does not Exist.')
    return render(request, 'talkingtree/myquestions.html', {
       'all_questions': questions, 'count_question': count_question,})


def searchquestions(request):
    try:
        search_text = request.GET.get('q')
        que = Question()
        questions = que.search(search_text=search_text)
    except Question.DoesNotExist:
        raise Http404('Answer Does not Exist.')
    return render(request, 'talkingtree/index.html', {
       'questions': questions, 'is_search_result': True, 'count_questions':questions.count()})

talkingtree/templates/talkingtree/answer.html
 {% extends 'talkingtree/base.html' %}
 {%  block title %} Question List {% endblock %}
 {%  block body %}

    <h4> Question: {{ question.question_text }}</h4>


    {% if all_answer %}
        <h4> List of Answers:[{{ count_answer }}] </h4>
        <ul>
            {% for answer in all_answer %}
            <li>
            <div class="well" style="border: 0.5px solid gray;  font-size: 1.2em;  background-color: #eeeeee ">
                <div class="row">
                    <div class="" style="margin-left: 5px; color:black">
                        <div  class="col-sm-12">
                            <a href="{% url 'talkingtree:comment' question.id answer.answer.id %}" style="margin-left: 5px; color:black"> {{ answer.answer.answer_text }}</a>
                        </div>
                    </div>
                </div>
            <div class="row" style="margin-left: 5px">
                <h6> Auther: {{  answer.answer.user  }} <br>
                     Date: {{ answer.answer.created_date }}
                </h6>
            </div>

                <div class="row">
                    <div class="col-sm-2">
                        <form action="{% url 'talkingtree:upvotes_answer' answer.answer.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit"
                                    {% if answer.vote == True %}
                                        class="btn btn-primary btn-xs"
                                    {% else %}
                                        class="btn btn-denser btn-xs"
                                    {% endif %}>
                                <span class="glyphicon glyphicon-arrow-up"></span>
                                . Upvote . {{ answer.count_upvoteanswer }}
                            </button>
                        </form>
                    </div>

                    <div class="col-sm-2">
                        <form action="{% url 'talkingtree:downvotes_answer' answer.answer.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit"
                                    {% if answer.vote == False %}
                                        class="btn btn-primary btn-xs"
                                    {% else %}
                                        class="btn btn-denser btn-xs"
                                    {% endif %}>
                                <span class="glyphicon glyphicon-arrow-down"></span>
                                . Downvote . {{ answer.count_downvoteanswer }}
                            </button>
                        </form>
                    </div>

                    {% if  user.is_authenticated and answer.answer.user == user %}
                        <div class="col-sm-1">
                            <form method="POST" action="{% url 'talkingtree:delete-answer' question.id  answer.answer.id  %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-dense btn-xs">
                                    <span  class="glyphicon glyphicon-trash" aria-hidden="true"> </span>
                                </button>
                            </form>
                        </div>
                    <div class="col-sm-1">
                        <div class="row">
                            <a href="{% url 'talkingtree:update-answer' question.id answer.answer.id  %}" class="btn btn-info btn-xs">
                                Update
                                <span  class="glyphicon glyphicon-pencil" aria-hidden="true"> </span></a>
                            </a>
                        </div>
                    </div>
                {% endif %}

                {% if user.is_authenticated %}
                    <div  class="col-sm-1">
                        <a href="{% url 'talkingtree:add-comment' question.id answer.answer.id  %}" class="btn btn-info btn-xs">
                        Comment
                        <span  class="glyphicon glyphicon-pencil" aria-hidden="true"> </span></a>
                    </div>
                {% endif %}
                </div>
            </div>
            </li>
            {% endfor %}
        </ul>

        {% else %}
       <div class="alert alert-danger">
        No answer found. People are searching for a better answer to this question.
       </div>
    {% endif %}
             <div class="well row" style="margin-left: 5px">
                 {% if user.is_authenticated %}
                    <div  class="col-sm-9"><a href="{% url 'talkingtree:add-answer' question.id %}">
                        Answer this question
                        <span  class="glyphicon glyphicon-pencil" aria-hidden="true"> </span></a>
                    </div>
                 {% endif %}
                <div  class="col-sm-3">
                    <a href="/talkingtree/"> Back to home page  <span  class="glyphicon glyphicon-home" aria-hidden="true"> </span></a>
                </div>
            </div>

 {% endblock %}


talkingtree/templates/talkingtree/answer_confirm_delete.html
<div class="well">
    <form action="" method="">

    confirm delete
<button type="submit">Yes</button>
    </form>
</div>

talkingtree/templates/talkingtree/base.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{%  block title %} Talking Tree {% endblock %}
    </title>

      {% load staticfiles %}
      <link rel="stylesheet" type="text/css" href="{% static 'talkingtree/style.css' %}">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">

    </head>
    <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'talkingtree:question' %}">
              <span  class="glyphicon glyphicon-tree-deciduous" aria-hidden="true"></span>TalkingTree</a>
        </div>
        <ul class="nav navbar-nav ">
          <li> <a class="navbar-brand" href="{% url 'talkingtree:question' %}">
              Questions  <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
          </a></li>
         {% if user.is_authenticated %}
            <li>
              <a class="navbar-brand" href="{% url 'talkingtree:add-question' %}">
                     Add Question <span  class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              </a>
            </li>
         {% endif %}

        </ul>
          <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'talkingtree:searchquestions' %}">
            <input type="text" class="form-control" name = "q" value="" placeholder="search a question" required>
             <button class="form-control btn btn-info" name = "searchBtn" >Search Question
             <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
             </button>
          </form>
          <ul class="nav navbar-nav navbar-right">


                    {% if user.is_authenticated %}
                       <li>
                           <a class="navbar-brand" href="{% url 'talkingtree:myquestions' %}">
                                My Questions
                                <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
                            </a>
                       </li>
                        <li>
                           <a class="navbar-brand" href="{% url 'talkingtree:myanswers' %}">
                                My Answers
                                <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
                            </a>
                       </li>
                      <li class="">
                            <a class="navbar-brand" href="{% url 'talkingtree:profile' %}">
                                Profile <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            </a>
                      </li>
                        <li class="">
                         <div class="navbar-brand">
                            Hi {{ user.username }}!
                            </div>
                        </li>
                        <li>
                            <a class="navbar-brand" href="{% url 'talkingtree:logout' %}">
                                Logout  <span  class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            </a>
                        </li>
                        {% else %}
                        <li class="">
                          <a class="navbar-brand" href="{% url 'talkingtree:register' %}">Register</a>
                        </li>
                        <li class="">
                          <a class="navbar-brand" href="{% url 'talkingtree:login' %}">Login</a>
                        </li>
                    {% endif %}


              <li></li>
          </ul>
      </div>
    </nav>
    <div style="margin: 5px 250px 250px 250px;">
        {% block body %}
        {% endblock %}

{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
    </div>

    </body>
    </html>

talkingtree/templates/talkingtree/comment_confirm_delete.html
<div class="well">
    <form action="" method="">

    confirm delete
<button type="submit">Yes</button>
    </form>
</div>

talkingtree/templates/talkingtree/index.html
 {% extends 'talkingtree/base.html' %}
 {%  block title %} Question List {% endblock %}
 {%  block body %}
     {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'talkingtree/style.css' %}">

     {% if not user.is_authenticated %}
     <div class="well">
         <p><strong>TalkingTree </strong> is a place to share knowledge and better understand the world. You can ask a question and you can give answer to others questions ans you can also comment on an answer.</p>
     </div>
    {% endif %}

     {% if is_search_result == True %}
        <h3> Search result </h3> Search result : {{ count_questions }} [ Ordered by : Most recent first ]
         {% if count_questions == 0 %}
             <div class="well">
                    No search result found. Please change your search keyword and try again.
             </div>
          {% endif %}
     {% else %}
         <h3> List of Questions </h3> [ Ordered by : Most recent first ]
     {% endif %}
    <ul>
        {% for question in questions %}
        <li>
        <div class="well">

        <div class="row" style="margin-left: 5px">
            <div  class="col-sm-12">
                <a href="{% url 'talkingtree:answer' question.id %}">
                <span class="question" style="font-weight:bold;  font-size: 1.5em; color:black">
                    {{ question.question_text }}
                </span>
                </a>
                <br>
                <h6>Question requested by: {{ question.user }} on {{ question.created_date }}</h6>
            </div>
        </div>
            <div class="row"  style="margin: 5px 5px 5px 5px">
            {% if question.user == user %}
                <div class="col-sm-1">

                <form method="POST" action="{% url 'talkingtree:delete-question'  question.id  %}">
                    {% csrf_token %}
                    <button class="btn btn-denser btn-xs" type="submit" value="Delete">
                        <span  class="glyphicon glyphicon-trash" aria-hidden="true"> </span>
                    </button>
                </form>
            </div>

             <div  class="col-sm-2">
                 <a  href="{% url 'talkingtree:update-question' question.id  %}"  class="btn btn-info btn-xs"> Update
                <span  class="glyphicon glyphicon-pencil" aria-hidden="true"> </span>
            </a>
            </div>
            {% endif %}
                {% if user.is_authenticated %}
                    <div  class="col-sm-2">
                        <a href="{% url 'talkingtree:add-answer' question.id %}" role="button"  class="btn btn-info btn-xs"> Answer
                        <span  class="glyphicon glyphicon-pencil" aria-hidden="true"> </span>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
        </li>
        {% endfor %}
    </ul>

 {% endblock %}

talkingtree/templates/talkingtree/question_confirm_delete.html
<div class="well">
    <form action="" method="">

    confirm delete
<button type="submit">Yes</button>
    </form>
</div>